### ISSUE TITLE
feedback HW 7

### ISSUE THREAD

**Issue by LVALL** [EugeneShitov/RailsHW#4]
Перший пункт завдання виконаний некоректно. Ви забули про створення допоміжної таблиці, що повинна слугувати для зв'язку між моделями з `has_and_belongs_to_many` асоціацією.

- [x] почитайте про те, як здійснюється зв'язок has and belongs to many, чому недостатньо прописати його лише на рівні ActiveRecord, та як він взагалі працює. Ось [стаття](https://patilshekhar900.medium.com/has-many-belongs-to-many-in-rails-5-4705a0e4bec), якраз про теги та пости. Також прогляньте зв'язок `has_many through` [тут](https://www.ducktypelabs.com/how-a-has_many-through-association-works-in-practice/)

- [x] реалізація контролеру лайків `LikesController`, чому в ній пропущено обробку негативного кейсу для методів `create` та `destroy` ? В інших контролерах CRUD-методи описані коректно.

- [x] метод `destroy`

```
  def destroy
    @like = Like.find(params[:id]).destroy

    render json: { message: "Like (#{@like}) destroyed!" }
  end
```
По-перше, після видалення об'єкту ми не повинні на нього посилатись, і якимось чином його повертати.
По-друге, навіть якщо Ви скористались властивістю методу `destroy` повертати видалений об'єкт, не думаю, що варто інтерполяцією поміщати його повністю в меседж.

у разі невдалого видалення тут буде меседж "Like false destroyed!" ?

Подумайте над логікою роботи методу, та спробуйте коректно опрацювати видалення

**Comment by EugeneShitov** [comment]
Дякую за пояснення.
Зробив зміни, начебто все працює як треба.
